export const dueActionTypes = {
    GET_DUE_START: 'GET_DUE_START',
    GET_DUE_SUCCESS: 'GET_DUE_SUCCESS',
    GET_DUE_FAILURE: 'GET_DUE_FAILURE',
    SET_PREV_DOC: 'SET_PREV_DOC',
    GET_MORE_START: 'GET_MORE_START',
    GET_MORE_SUCCESS: 'GET_MORE_SUCCESS',
    GET_MORE_FAILURE: 'GET_MORE_FAILURE',
}