export const registerActionTypes = {
    REGISTER_ICT_START: 'REGISTER_ICT_START',
    REGISTER_ICT_SUCCESS: 'REGISTER_ICT_SUCCESS',
    REGISTER_ICT_FAILURE: 'REGISTER_ICT_FAILURE',
    REGISTER_STAFF_START: 'REGISTER_STAFF_START',
    REGISTER_STAFF_SUCCESS: 'REGISTER_STAFF_SUCCESS',
    REGISTER_STAFF_FAILURE: 'REGISTER_STAFF_FAILURE'
}