export const dueTodayActionTypes = {
    GET_DUE_TODAY_START: 'GET_DUE_TODAY_START',
    GET_DUE_TODAY_SUCCESS: 'GET_DUE_TODAY_SUCCESS',
    GET_DUE_TODAY_FAILURE: 'GET_DUE_TODAY_FAILURE',
    SET_DUE_TODAY_PREV_DOC: 'SET_DUE_TODAY_PREV_DOC',
    GET_DUE_MORE_START: 'GET_DUE_MORE_START',
    GET_DUE_MORE_SUCCESS: 'GET_DUE_MORE_SUCCESS',
    GET_DUE_MORE_FAILURE: 'GET_DUE_MORE_FAILURE',
}