export const ticketActionTypes = {
    GET_TICKET_START: 'GET_TICKET_START',
    GET_TICKET_SUCCESS: 'GET_TICKET_SUCCESS',
    GET_TICKET_FAILURE: 'GET_TICKET_FAILURE',
    ASSIGN_TICKET_START: 'ASSIGN_TICKET_START',
    ASSIGN_TICKET_SUCCESS: 'ASSIGN_TICKET_SUCCESS',
    ASSIGN_TICKET_FAILURE: 'ASSIGN_TICKET_FAILURE'
}