export const uncompletedActionTypes = {
    GET_UNCOMPLETED_START: 'GET_UNCOMPLETED_START',
    GET_UNCOMPLETED_SUCCESS: 'GET_UNCOMPLETED_SUCCESS',
    GET_UNCOMPLETED_FAILURE: 'GET_UNCOMPLETED_FAILURE',
    SET_PREV_DOC: 'SET_PREV_DOC',
    GET_MORE_UNCOMPLETED_START: 'GET_MORE_UNCOMPLETED_START',
    GET_MORE_UNCOMPLETED_SUCCESS: 'GET_MORE_UNCOMPLETED_SUCCESS',
    GET_MORE_UNCOMPLETED_FAILURE: 'GET_MORE_UNCOMPLETED_FAILURE'
}