export const unassignedActionTypes = {
    GET_UNASSIGNED_START: 'GET_UNASSIGNED_START',
    GET_UNASSIGNED_SUCCESS: 'GET_UNASSIGNED_SUCCESS',
    GET_UNASSIGNED_FAILURE: 'GET_UNASSIGNED_FAILURE',
    SET_PREV_DOC: 'SET_PREV_DOC'
}