export const unassignedActionTypes = {
    GET_UNASSIGNED_START: 'GET_UNASSIGNED_START',
    GET_UNASSIGNED_SUCCESS: 'GET_UNASSIGNED_SUCCESS',
    GET_UNASSIGNED_FAILURE: 'GET_UNASSIGNED_FAILURE',
    SET_UNASSIGNED_PREV_DOC: 'SET_UNASSIGNED_PREV_DOC',
    GET_MORE_UNASSIGNED_START: 'GET_MORE_UNASSIGNED_START',
    GET_MORE_UNASSIGNED_SUCCESS: 'GET_MORE_UNASSIGNED_SUCCESS',
    GET_MORE_UNASSIGNED_FAILURE: 'GET_MORE_UNASSIGNED_FAILURE',
}